title: ExproStone
email: export@exprostone.com
description: "B2B Export of Building Stones, Tiles, and Steel to Iraq & Kuwait"
baseurl: "/export-stone-tiles" # Set to repository name for GitHub Project Pages
url: "" 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  products:
    output: true
    permalink: /products/:path/

# Site Data
brands:
  tiles:
    - Kasra
    - Alborz
    - MahCeram
    - Aghigh
    - EfaCeram
    - Goldis
  stones:
    - Travertine (Abbas Abad, Darreh Bokhari)
    - Marble (Isfahan)
    - Granite (Natanz, Zahedan)

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
